// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/****************************************************************************************
 *                            NOTICE: AUTO-GENERATED                                    *
 ****************************************************************************************
 * This file is automatically generated by script "./src/question/generator.ts".        *
 * Please don't manually change its contents, as any modifications will be overwritten! *
 ***************************************************************************************/

import { CLICommandOption, CLICommandArgument } from "@microsoft/teamsfx-api";

export const AddAuthActionOptions: CLICommandOption[] = [
  {
    name: "plugin-manifest-path",
    type: "string",
    description: "Plugin manifest path.",
    required: true,
  },
  {
    name: "openapi-spec-location",
    type: "string",
    description: "OpenAPI specification to add Auth configuration.",
  },
  {
    name: "api-operation",
    type: "array",
    description: "API to add Auth configuration.",
  },
  {
    name: "auth-name",
    type: "string",
    description: "Name of Auth Configuration.",
    required: true,
  },
  {
    name: "api-auth",
    type: "string",
    description: "The authentication type for the API.",
    required: true,
    default: "none",
    choices: ["none", "api-key", "bearer-token", "microsoft-entra", "oauth"],
  },
];
export const AddAuthActionArguments: CLICommandArgument[] = [];
