// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/****************************************************************************************
 *                            NOTICE: AUTO-GENERATED                                    *
 ****************************************************************************************
 * This file is automatically generated by script "./src/question/generator.ts".        *
 * Please don't manually change its contents, as any modifications will be overwritten! *
 ***************************************************************************************/

import { Inputs } from "@microsoft/teamsfx-api";

export interface AddAuthActionInputs extends Inputs {
  /** @description Import Manifest File */
  "plugin-manifest-path"?: string;
  /** @description Select an OpenAPI Description Document */
  "openapi-spec-location"?: string;
  /** @description Select an API to Add Auth Configuration */
  "api-operation"?: string[];
  /** @description Input the Name of Auth Configuration */
  "auth-name"?: string;
  /** @description Authentication Type */
  "api-auth"?: "none" | "api-key" | "bearer-token" | "microsoft-entra" | "oauth";
}
