name: CD
run-name: CD-${{ github.run_id }}-${{ github.ref_name }}-${{ inputs.preid }}
on:
  workflow_dispatch:
    inputs:
      preid:
        description: "preid name(alpha, beta, rc, stable)"
        required: true
        default: "rc"
      skip-version-rc:
        description: "release RC version just with lerna publish, skip run lerna version(yes or no)"
        required: false
        default: "no"
      pkgs:
        type: string
        required: false
        description: "Please enter the package names you want to publish, such as cli, vscode, sdk, server and template. Please separate multiple entries with spaces"
  schedule:
    - cron: "0 0 * * *"

jobs:
  cd:
    runs-on: ubuntu-latest
    env:
      CI: true
      PREID: ${{ github.event.inputs.preid }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Setup project
        run: |
          npm run setup
        env:
          REQUEST_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup git
        run: |
          git config --global user.name 'MSFT-yiz'
          git config --global user.email 'yiz@microsoft.com'

      - name: release alpha npm packages to npmjs.org
        if: ${{ github.ref == 'refs/heads/dev' }}
        run: |
          npx lerna version prerelease --preid=alpha.$(git rev-parse --short HEAD) --exact --no-push --allow-branch dev --yes

      - name: release beta packages to npmjs.org
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'beta' }}
        run: |
          npx lerna version prerelease --preid=beta.$(date "+%Y%m%d%H") --exact --no-push --allow-branch ${GITHUB_REF#refs/*/} --yes

      - name: version rc npm packages to npmjs.org
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'rc' && github.ref == 'refs/heads/main' && github.event.inputs.skip-version-rc == 'no'}}
        run: |
          npx lerna version prerelease --conventional-prerelease --preid=rc --no-changelog --yes

      - name: version rc npm packages to npmjs.org on hotfix
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'rc' && startsWith(github.ref, 'refs/heads/hotfix/') && github.event.inputs.skip-version-rc == 'no'}}
        run: |
          npx lerna version prerelease --conventional-prerelease --preid=rc-hotfix --no-changelog --allow-branch ${GITHUB_REF#refs/*/} --yes

      - name: version stable npm packages to npmjs.org
        if: ${{ github.event_name == 'workflow_dispatch' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/hotfix/')) && github.event.inputs.preid == 'stable' }}
        run: |
          npx lerna version --conventional-commits --conventional-graduate --no-changelog --allow-branch ${GITHUB_REF#refs/*/} --yes

      - name: version change
        id: version-change
        run: |
          echo "CHANGED=$(git tag --points-at HEAD | xargs)" >> $GITHUB_OUTPUT
          echo "TEMPLATE_VERSION=$(git tag --points-at HEAD | grep templates)" >> $GITHUB_OUTPUT
          echo "EXTENSION_VERSION=$(git tag --points-at HEAD | grep ms-teams-vscode-extension@)" >> $GITHUB_OUTPUT
          if git tag --points-at HEAD | grep templates | grep rc;
          then
              git push -d origin $TEMPLATE_VERSION
          fi

      - name: generate templates v3
        run: |
          .github/scripts/template-zip-autogen-v3.sh $TEMPLATE_PATH
          cd ./packages/fx-core
          rm -rf ./templates/fallback
          node ./scripts/download-templates-zip.js
        env:
          TEMPLATE_PATH: ${{ runner.temp }}/teamsfx_templates_v3

      - name: update templates beta tag
        uses: richardsimko/update-tag@v1
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'templates@') && github.event.inputs.preid == 'beta' }}
        with:
          tag_name: "templates-0.0.0-beta"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: release templates' beta version to github
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'templates@') && github.event.inputs.preid == 'beta' }}
        uses: ncipollo/release-action@v1.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          tag: "templates-0.0.0-beta"
          artifacts: ${{ runner.temp }}/teamsfx_templates_v3/*.zip
          allowUpdates: true
          removeArtifacts: true

      - name: update template rc tag
        uses: richardsimko/update-tag@v1
        if: ${{ (contains(steps.version-change.outputs.CHANGED, 'templates@') || contains(steps.version-change.outputs.CHANGED, '@microsoft/teamsfx')) && github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'rc' }}
        with:
          tag_name: "templates@0.0.0-rc"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: release templates' RC version to github
        if: ${{ (contains(steps.version-change.outputs.CHANGED, 'templates@') || contains(steps.version-change.outputs.CHANGED, '@microsoft/teamsfx')) && github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'rc' }}
        uses: ncipollo/release-action@v1.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          tag: "templates@0.0.0-rc"
          artifacts: ${{ runner.temp }}/teamsfx_templates_v3/*.zip
          allowUpdates: true
          removeArtifacts: true

      - name: Create Templates Stable Release
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'templates@') && github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'stable' }}
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: ${{ runner.temp }}/teamsfx_templates_v3/*.zip
          name: "Release for ${{ steps.version-change.outputs.TEMPLATE_VERSION }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.version-change.outputs.TEMPLATE_VERSION }}
          allowUpdates: true

      - name: Generate Tag List
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'templates@') && github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'stable' }}
        run: git tag | grep templates > ${{ runner.temp }}/template-tags.txt

      - name: Update Template Tag list Release
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'templates@') && github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'stable' }}
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: ${{ runner.temp }}/template-tags.txt
          name: "Template Tag List"
          body: "Release to maintain template tag list."
          token: ${{ secrets.github_token }}
          tag: "template-tag-list"
          allowUpdates: true


      - name: publish alpha release to npm org
        if: ${{ github.ref == 'refs/heads/dev'}}
        run: |
          npx lerna publish from-package --dist-tag=alpha --yes --allow-branch dev
        env:
          TEMPLATE_PATH: ${{ runner.temp }}/teamsfx_templates_v3

      - name: publish rc npm packages to npmjs.org
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'rc' }}
        run: |
          npx lerna publish from-package --dist-tag=rc --yes
        env:
          TEMPLATE_PATH: ${{ runner.temp }}/teamsfx_templates_v3

      - name: publish stable npm packages to npmjs.org
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'stable' }}
        run: |
          npx lerna publish from-package --yes
        env:
          TEMPLATE_PATH: ${{ runner.temp }}/teamsfx_templates_v3

      - name: pack vsix
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'ms-teams-vscode-extension@') }}
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 10
          retry_on: error
          command: |
            sleep 20
            cd ./packages/vscode-extension
            npm install --only=production
            if [ "$PREID" == "beta" ]
              npx vsce package --pre-release
            else
              npx vsce package 

      - name: release stable VSCode extension to github
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'ms-teams-vscode-extension@') && github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'stable' }}
        uses: ncipollo/release-action@v1.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.version-change.outputs.EXTENSION_VERSION }}
          artifacts: ./packages/**/*.vsix
          artifactErrorsFailBuild: true
          bodyFile: ./CHANGELOG.md

      - name: save release info
        run: |
          rm -f changed.txt
          rm -f versions.json
          echo ${{steps.version-change.outputs.CHANGED}} > changed.txt
          npx lerna ls -all --json > versions.json
          find ./packages/vscode-extension -type f -name '*.vsix' -exec mv {} . \;
          find ./packages/server/lib -type f -name '*.exe' -exec mv {} server.exe \;

      - name: upload release info to artifact
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: |
            changed.txt
            versions.json
            *.vsix
            *.exe
