name: CD

on:
  workflow_dispatch:
    inputs:
      preid:
        description: "preid name(alpha, prerelease, rc, stable)"
        required: true
        default: "rc"
      skip-version-rc:
        description: "release RC version just with lerna publish, skip run lerna version(yes or no)"
        required: false
        default: "no"
      pkgs:
        type: string
        required: false
        description: "Please enter the package names you want to publish, such as cli, vscode, sdk, server and template. Please separate multiple entries with spaces"
  schedule:
    - cron: "0 0 * * *"

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.github_token }}
          ref: ${{ github.ref }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: setup 
        run: |
          npm run setup

      - name: pack vsix
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 10
          retry_on: error
          command: |
            sleep 20
            cd ./packages/vscode-extension
            npm install --only=production
            npx vsce package --pre-release

      - name: save release info
        run: |
          rm -f changed.txt
          rm -f versions.json
          npx lerna ls -all --json > versions.json
          find ./packages/vscode-extension -type f -name '*.vsix' -exec mv {} . \;
          find ./packages/server/lib -type f -name '*.exe' -exec mv {} server.exe \;

      - name: upload release info to artifact
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: |
            changed.txt
            versions.json
            *.vsix
            *.exe

