name: publish to VSCode marketplace

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: "Input the CD pipeline run ID to fetch the artifact"
        required: true
        default: ""
      isPreview:
        description: "Publish VSIX as a preview version(yes or no)"
        required: true
        default: "no"

jobs:
  publish-to-vscode-marketplace:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}

      - name: get vsc version
        id: vsc_ver
        run: |
          VSC_VER=$(npx lerna ls --json -all|jq -c -r '.[]|select(.name == "ms-teams-vscode-extension")|.name+"-"+.version')
          echo "::set-output name=vsc_ver::$VSC_VER"
      
      - uses: mathieudutour/github-tag-action@v6.0
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.vsc_ver.outputs.vsc_ver }}
          tag_prefix: ""